name: first workflow
on:
  push:
    branches:
      - "main"

jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: ls before checkout
        run: ls -a
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v4

      - name: ls after checkout
        run: ls -a
        shell: bash